name: Build and Publish
on: [push]
jobs:
  build_vue:
    name: build
    runs-on: ubuntu-latest 
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: git cmd setup
      run: |
        git config --global user.email "${{ github.actor }}"
        git config --global user.name "${{ github.actor }}@users.noreply.github.com"
    - run: npm i
    - run: npm run build
      env:
        VITE_GOOGLE_SHEETS_ID: ${{ secrets.VITE_GOOGLE_SHEETS_ID }}
        VITE_TWITCH_CLIENT_ID: ${{ secrets.VITE_TWITCH_CLIENT_ID }}
        VITE_TWITCH_CLIENT_SECRET: ${{ secrets.VITE_TWITCH_CLIENT_SECRET }}
        VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
    - name: ghPages (w/404hack)
      run: |
        cd dist
        ln -s index.html 404.html
        git init
        git add -A
        git commit -m "autoPublish: ${{ github.sha }}"
        git push -f https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git master:gh-pages